language: go

go:
  - '1.7.3'

before_install:
  - go get github.com/mitchellh/gox

script:
  - .travis/build.sh

env:
  global:
    - OS_TARGETS="linux darwin windows"
    - ARCH_TARGETS="386 amd64"
