language: go

go:
  - '1.7.3'

install:
  # Install godep
  - go get github.com/tools/godep
  # Intall project dependencies using godep
  - godep restore
  # Install gox cross compile tool
  - go get github.com/mitchellh/gox

script:
  - .travis/build.sh

env:
  global:
    - OS_TARGETS="linux darwin windows"
    - ARCH_TARGETS="386 amd64"
