language: go

go:
  - '1.10.1'

addons:
  apt:
    packages:
      - curl
      - p7zip-full

install:
  # Install dep
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  # Intall project dependencies using dep
  - dep ensure -v
  # Install gox cross compile tool
  - go get github.com/mitchellh/gox
  # Install Node.js and NPM (reequired by snyk)
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  # Install snky
  - sudo npm install -g snyk

script:
  - .travis/build.sh
  - snyk test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - snyk monitor --org=gantsign --project-name=alt-galaxy

branches:
  only:
    - master
    - /^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)([\.\-].*)?$/

deploy:
  provider: releases
  api_key:
    secure: G3DYud9uAw2hnoqPmMHTi29i9fC8h3+NWRZdCNit8dEC9ahuq7CB7YCXqhdmW0j1kx4/W2EogONqCKpvSHZxJ9JGev4y8GvXF1Sb8X4ACBVHIH5YWh4V18JQE6dlsC7/1tiW0H3SUjiSY4BY3aSFjJFaR6ojvzKXKYgXWq2dW5hPOWK/86ewJRFNAiKsa4dSxwwMMwVkyaYy4ZfnoS2VCdu4txiT5yl0CbYjqgiK4AN9P/v/RZNQw426EdLFROTGz19g8toG6GNseSsoN50BhI3ten0sFxlgJCn73ssXhXMexIyrfP3dj1R9/8oSJDao/8WkVE9Im9DqtbUfPWWuA4NDnkLE3Ro3wa6oT8yzepmEy4uap948azXQBQDPzqR3uPwX3bLFkTdxc1NZFp6Q3edODH7RBmAyHEHD/6nFOaLUje/k8EeJRXQONaxJl25yAPVx2MMk3V8sr2q01MlyfKbnmV50WrbxTa5hmTj8cUrq+02TfsGHT512cs2nMx6VPnGVei4+0nGlN7Ry4T63Cnh7dd1UBORIsaC4WCZiv1P1V5aD4iw6rEUmMGD6p2LOLxNzfM4PwRs5OSt5FnW4KOmiF9IKhivxK+PXajEZAcZcluddXZ2UN6lDqfdFddvTqkueWOqeqHD/1hg5l7RN6J9RxnOMXEG4/AcgruBEgBI=
  file:
    - dist/alt-galaxy_linux_386.tar.xz
    - dist/alt-galaxy_linux_amd64.tar.xz
    - dist/alt-galaxy_darwin_amd64.tar.gz
    - dist/alt-galaxy_windows_386.7z
    - dist/alt-galaxy_windows_amd64.7z
  skip_cleanup: true
  on:
    repo: gantsign/alt-galaxy
    tags: true

env:
  global:
    - OS_TARGETS="linux darwin windows"
    - ARCH_TARGETS="386 amd64"
    # snky token
    - secure: 0q1S1KMgq+i63sFmiEjqwICZ/nfjlpKVb535uGIqwcVXqlT7yW/If6vOw7YsijWoLP50RMeIy6Ur8ecPwXT04BjaO8h+Z3f9mAVlsB44EeUrkGc9yFkaQZvDeMyTWtLnPka3CDC2OKSsZzSu/mn6I1iyxZmOo/Divpql8Imi3I5RxQDae3kMP0maeUArYq54um3fFsiZm4u5RNojnPNojFP/e9pNFHMa1gyV1YrpvxGMUDQezoPq3gcalnc84/g4xKkn521SdaKj5Qz0i2Kvf7gUAUPg9uxR/s1FNKwdM7bPrvkdyg9APGEsdHwIbpOyVAD2J7hinhN1ahSqWnLz/DtxAyNsAXdXyFVwDP6fXQCB25coODDRRfsZkGu8veLelraFLhrLCY0gM1vn+ecNZD9EhtRJCvqEcKSZk17dbT76EwIDc+VJAE8kbfYnt3VK1LR1MSX/+b7AeLXvUaN1QJmOfECwbI0ZDsQd3WBMcgGjz7BQ3RZysv7Zh7vgtOBfOY7gXTzlOIKovevkaJODAEFOQgJomFnKnkBXooLaF2HJ7GjLD3J9VkowshP4nAmS4n07E5Y08o4g7UamJryGC0yyuEp4NphV+uKFhNFdbaKDgF1dOncWAGv7sI6H06y8u7pgNsLGF8GyqRPaKrOPuwTNuhbAqdsbTNfS5l8CwJM=
