language: go

go:
  - '1.7.4'

addons:
  apt:
    packages:
      - p7zip-full

install:
  # Install godep
  - go get github.com/tools/godep
  # Intall project dependencies using godep
  - godep restore
  # Install gox cross compile tool
  - go get github.com/mitchellh/gox

script:
  - .travis/build.sh

branches:
  only:
    - master
    - /^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)([\.\-].*)?$/

deploy:
  provider: releases
  api_key:
    secure: F/Sj5uG2HTFKsAt1Ns4SYOlapXnFC8Y+1lErvup3JVtc1qZ0tAW4xD5konSQBtMD6S06z12mZbSlGqUMnBq885RdJQKgg7H15p/che5o56jNDTZ3cncH93Ows6WRmor8LWXq1oq39i+N+edTdb4DCO+YBwGj9e1oFT1yXbZXmB6dUvH1JiVbdNJYoF7Qr360Tbv34nlt1EKtGtKFcusdbn++OtzkTJIpP6bYFng5w4YD5P345xOWuwmrG67LdzNlN9TVfFhuDvwDzeEtQOc62JAJkxt8SvKIbT3YFbZDzkPelkJTt02zVpUyRvpMvojkM54Vx20rzApAf94sQ9fa3VE5M98cwErsu7MacKU+Z0cJvIovIQmmRnWELmbRyhxnC9VFG1yzXXQJzBuv01mkDp79cOMzXFAMbl/poNlOzr0w0DoJzYGUgsFTX2Y47rm0nLcGkScxafW3waQY5gJhjpDGLF8O8Nv9nldHYrl1pYByGdCZr2r6SiEvbKi21a8oiG1U9z/xUmNqxvbr0DqisVzrrBEb4UzC18YeJv/MKrwhNsMkh8XkYBu4P+Q5jLx7WLVmOLdgrj0oADQa/YmrvOUrD2FZI89Wb2ydZF+CdkNs3ksf3a3l4ShvDouBk0tn2bCci8IbcuczNnj9G3I2uY09gx9z1LoGjtdNXfLkP2o=
  file:
    - dist/alt-galaxy_linux_386.tar.xz
    - dist/alt-galaxy_linux_amd64.tar.xz
    - dist/alt-galaxy_darwin_amd64.tar.gz
    - dist/alt-galaxy_windows_386.7z
    - dist/alt-galaxy_windows_amd64.7z
  skip_cleanup: true
  on:
    repo: gantsign/alt-galaxy
    tags: true

env:
  global:
    - OS_TARGETS="linux darwin windows"
    - ARCH_TARGETS="386 amd64"
